fail_fast: true
repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff-lint
        language: system
        entry: poetry run ruff
        args: [check, --fix]
        types: [python]
        always_run: true
      - id: ruff-format
        name: ruff-format
        language: system
        entry: poetry run ruff
        args: [format]
        types: [python]
        always_run: true