name: Deploy to Docker

on:
  push:
    tags:
      - '**'

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build-n-deploy:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          # Check this before edit github.ref_name env: https://stackoverflow.com/a/69919067
          tags: |
            clooooode/fomo-bot:${{ github.ref_name }}
            clooooode/fomo-bot:latest
      
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          fromTag: ${{ github.event.release.tag_name }}
          toTag: ${{ github.ref_name }}

      - name: Create Release Assets
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
          draft: false
          prerelease: false